routes/web.php
<?php

use App\Http\Controllers\ArticleController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

require __DIR__.'/auth.php';

Route::get('/',[HomeController::class,'index'])->name('home');

Route::middleware(['auth'])->group(function (){
    Route::prefix('/article')->name('article.')->group(function (){
          Route::get('/',[ArticleController::class,'index'])->name('index');
        Route::get('/form',[ArticleController::class,'create'])->name('create');
        Route::post('/',[ArticleController::class,'store'])->name('store');
        Route::get('/edit/{id}',[ArticleController::class,'edit'])->name('edit');
        Route::put('/',[ArticleController::class,'update'])->name('update');
        Route::get('/delete{id}',[ArticleController::class,'destroy'])->name('delete');
    });
});


Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    use HasFactory;
    public function user()
    {
        return $this->belongsTo(User::class);
    }
  protected $fillable=[
       'title',
      'description',
      'image'
  ];
    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }
}

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;
    public function articles()
    {
        return $this->belongsToMany(Article::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;
    const ROLE_USER='user';
    const ROLE_ADMIN='admin';
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function articles()
    {
        return $this->hasMany(Article::class);
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ArticleRequest;
use App\Http\Requests\EditArticleRequest;
use App\Models\Article;
use App\Models\Tag;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;


class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $id=Auth::id();
        $articles=Article::with('tags')
            ->where('user_id',$id)
            ->simplePaginate(2);

         return view('article.index',['articles'=>$articles]);


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|
     * \Illuminate\Contracts\View\Factory|
     * \Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        $tags=Tag::all();
        return view('article.create',['tags'=>$tags]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(ArticleRequest $request,Article $article)
    {
        try {
            DB::beginTransaction();
            $user=Auth::user();
            $article->user_id=$user->id;
            $article->title=$request->title;
            $article->description=$request->description;
            $article->image=$request->file('banner')->store('banners');


            $article->save();
            $article->tags()->attach($request->tags);
            DB::commit();
        }
        catch (Exception $ex){
            Log::error($ex);
            DB::rollBack();
        }


      return redirect()->route('article.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tags=Tag::all();
       $article=Article::findOrFail($id);
       return view('article.edit',['article'=>$article],['tags'=>$tags]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ArticleRequest $request)
    {
        try {
            DB::beginTransaction();
            $article=Article::findOrFail($request->id);
            $userId=Auth::id();
            If($article->user_id!==$userId){
                abort(403);
            }
            if($request->hasFile('image')){
                $image=$request->file('image')->store('banners');
                $previousImage=$article->image;
                $article->image=$image;

            }
            $article->title=$request->title;
            $article->description=$request->description;
            $article->save();
            if(isset($previousImage)){
                Storage::delete($previousImage);
            }
            $article->tags()->sync($request->tags);
            DB::commit();
        }  catch (Exception $ex){
            Log::error($ex);
            DB::rollBack();
        }

        return redirect(route('article.index'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            DB::beginTransaction();
            $article=Article::find($id);
            $userId=Auth::id();
            If($article->user_id!==$userId) {
                abort(403);
            }
            $article=Article::destroy($id);
            DB::commit();

        }
        catch (Exception $ex){
            Log::error($ex);
            DB::rollBack();
        }
        return redirect(route('article.index'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    public  function index(Request $request){
        return view('home');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/article/create.blade.php
@extends('layouts.master')

@section('title-block')
    Create article
@endsection

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <article>
        <form method="POST" action="{{route('article.store')}}" enctype="multipart/form-data">
            @csrf
            <header class="entry-header">
                <h1 class="entry-title">Create new article</h1><br>
                @error('title')
                <div>{{ $message }}</div>
                @enderror
                <h1 class="entry-title"><input type="text" name="title" value="">title</h1>
                <h1 class="entry-title"><input type="text" name="image" value="">image</h1>
                <div class="entry-thumbnail">
                    <h1 class="entry-title">Upload image</h1>
                    <input type="file" name="banner">
                </div>
                @error('file')
                <div>{{ $message }}</div>
                @enderror
            </header>
            <!-- .entry-header -->
            <div class="entry-content">
                @error('content')
                <div>{{ $message }}</div>
                @enderror
                <label>
                    <textarea rows="6" name="description">Enter text</textarea>
                </label>
            </div>
           <div class="entry-content" style="display: flex;flex-direction: column">
                @foreach($tags as $tag)

                        <input type="checkbox" id="{{$tag->name}}" name="tags[]" value="{{$tag->id}}">
                         <label for="{{$tag->name}}">{{$tag->name}}</label>
                @endforeach
            </div>
            <!-- .entry-content -->

            <!-- .entry-footer -->
            <button class="wpcmsdev-button color-violet hentry" type="submit">Create</button>
        </form>
    </article>
@endsection

resources/views/article/edit.blade.php
@extends('layouts.master')

@section('title-block')
    Create article
@endsection

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <article>
        <form method="POST" action="{{route('article.update')}}" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <input type="hidden" name="id" value="{{$article->id}}">
            <header class="entry-header">
                <h1 class="entry-title">Edit article</h1><br>
                @error('title')
                <div>{{ $message }}</div>
                @enderror
                <h1 class="entry-title"><input type="text" name="title" value="{{$article->title}}">title</h1>
                <h1 class="entry-title"><input type="text" name="image" value="{{$article->image}}">image</h1>
                <div class="entry-thumbnail">
                  <a href=""><img src="/public/storage/{{$article->image}}"></a>
                </div>
                <div class="entry-thumbnail">
                    <h1 class="entry-title">Upload image</h1>
                    <input type="file" name="banner">
                </div>
                @error('file')
                <div>{{ $message }}</div>
                @enderror
            </header>
            <!-- .entry-header -->
            <div class="entry-content">
                @error('content')
                <div>{{ $message }}</div>
                @enderror
                <label>
                    <textarea rows="6" name="description">{{$article->description}}</textarea>
                </label>
            </div>
            <div class="entry-content" style="display: flex;flex-direction: column">
                @foreach($tags as $tag)

                    <input type="checkbox" id="{{$tag->name}}" name="tags[]" value="{{$tag->id}}">
                    <label for="{{$tag->name}}">{{$tag->name}}</label>
                @endforeach
            </div>
            <!-- .entry-content -->

            <!-- .entry-footer -->
            <button class="wpcmsdev-button color-yellow hentry" type="submit">Edit</button>
        </form>
    </article>
@endsection

resources/views/article/index.blade.php
@extends('layouts.master')

@section('content')

                <div class="grid portfoliogrid" style="position: relative; height: 200px;">
                 @foreach($articles as $article)
                    <article class="hentry" style="position: absolute; left: 0px; top: 0px;">
                        <header class="entry-header">
                            <div class="entry-thumbnail">
                                <img src="/storage/{{$article->image}}" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="p1">
                            </div>
                            <h2 class="entry-title">
                                <a>{{$article->title}}</a>

                            </h2>
                            <h2 class="entry-title">
                                <a href="" rel="bookmark">{{$article->description}}</a>
                            </h2>
                            @foreach($article->tags as $tag)
                                <a>{{$tag->name}}</a>
                            @endforeach
                            <br>
                            
                            <a href="{{route('article.edit',['id'=>$article->id])}}" rel="bookmark" style="color: green">Edit</a><br>
                            <a href="{{route('article.delete',['id'=>$article->id])}}" rel="bookmark" style="color: red">Delete</a>
                        </header>
                    </article><br>

                    @endforeach

                </div>

                {{ $articles->links() }}
                <!-- .grid -->

{{--                <nav class="pagination">--}}
{{--                    <span class="page-numbers current">1</span>--}}
{{--                    <a class="page-numbers" href="#">2</a>--}}
{{--                    <a class="next page-numbers" href="#">Next »</a>--}}
{{--                </nav>--}}
                <br>


    <!-- .container -->
@endsection

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}

        </h2>
        <a href="{{route('index')}}">Home page</a>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/home.blade.php
@extends('layouts.master')

@section('title-block')
    Main page
@endsection

@section('content')

                <div class="grid portfoliogrid" style="position: relative; height: 200px;">

                    <article class="hentry" style="position: absolute; left: 0px; top: 0px;">
                        <header class="entry-header">
                            <div class="entry-thumbnail">
                                <a href="portfolio-item.html"><img src="http://s3.amazonaws.com/caymandemo/wp-content/uploads/sites/15/2015/09/30162427/p1.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="p1"></a>
                            </div>
                            <h2 class="entry-title"><a href="portfolio-item.html" rel="bookmark">Sunset Beach</a></h2>
                            <a class="portfoliotype" href="portfolio-category.html">summer</a>
                            <a class="portfoliotype" href="portfolio-category.html">woman</a>
                            <a class="portfoliotype" href="portfolio-category.html">yellow</a>
                        </header>
                    </article>

                    <article class="hentry" style="position: absolute; left: 291px; top: 0px;">
                        <header class="entry-header">
                            <div class="entry-thumbnail">
                                <a href="portfolio-item.html"><img src="http://s3.amazonaws.com/caymandemo/wp-content/uploads/sites/15/2015/09/30160348/p5.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="p1"></a>
                            </div>
                            <h2 class="entry-title"><a href="portfolio-item.html" rel="bookmark">Earl of Moreland</a></h2>
                            <a class="portfoliotype" href="portfolio-category.html">hat</a>
                            <a class="portfoliotype" href="portfolio-category.html">woman</a>
                            <a class="portfoliotype" href="portfolio-category.html">yellow</a>
                        </header>
                    </article>

                    <article class="hentry" style="position: absolute; left: 583px; top: 0px;">
                        <header class="entry-header">
                            <div class="entry-thumbnail">
                                <a href="portfolio-item.html"><img src="http://s3.amazonaws.com/caymandemo/wp-content/uploads/sites/15/2015/09/30160151/p3.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="p1"></a>
                            </div>
                            <h2 class="entry-title"><a href="portfolio-item.html" rel="bookmark">Eliza and John</a></h2>
                            <a class="portfoliotype" href="portfolio-category.html">summer</a>
                            <a class="portfoliotype" href="portfolio-category.html">woman</a>
                            <a class="portfoliotype" href="portfolio-category.html">yellow</a>
                        </header>
                    </article>

                    <article class="hentry" style="position: absolute; left: 0px; top: 100px;">
                        <header class="entry-header">
                            <div class="entry-thumbnail">
                                <a href="portfolio-item.html"><img src="http://s3.amazonaws.com/caymandemo/wp-content/uploads/sites/15/2015/09/18160911/p6.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="p1"></a>
                            </div>
                            <h2 class="entry-title"><a href="portfolio-item.html" rel="bookmark">Hot Afternoon</a></h2>
                            <a class="portfoliotype" href="portfolio-category.html">pink</a>
                            <a class="portfoliotype" href="portfolio-category.html">woman</a>
                            <a class="portfoliotype" href="portfolio-category.html">yellow</a>
                        </header>
                    </article>

                    <article class="hentry" style="position: absolute; left: 291px; top: 100px;">
                        <header class="entry-header">
                            <div class="entry-thumbnail">
                                <a href="portfolio-item.html"><img src="http://s3.amazonaws.com/caymandemo/wp-content/uploads/sites/15/2015/09/15223245/p2.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="p1"></a>
                            </div>
                            <h2 class="entry-title"><a href="portfolio-item.html" rel="bookmark">Long Walks</a></h2>
                            <a class="portfoliotype" href="portfolio-category.html">hat</a>
                            <a class="portfoliotype" href="portfolio-category.html">summer</a>
                            <a class="portfoliotype" href="portfolio-category.html">yellow</a>
                        </header>
                    </article>

                    <article class="hentry" style="position: absolute; left: 583px; top: 100px;">
                        <header class="entry-header">
                            <div class="entry-thumbnail">
                                <a href="portfolio-item.html"><img src="http://s3.amazonaws.com/caymandemo/wp-content/uploads/sites/15/2015/09/15222855/p7.jpg" class="attachment-post-thumbnail size-post-thumbnail wp-post-image" alt="p1"></a>
                            </div>
                            <h2 class="entry-title"><a href="portfolio-item.html" rel="bookmark">Twilight</a></h2>
                            <a class="portfoliotype" href="portfolio-category.html">hat</a>
                            <a class="portfoliotype" href="portfolio-category.html">woman</a>
                            <a class="portfoliotype" href="portfolio-category.html">summer</a>
                        </header>
                    </article>

                </div>
                <!-- .grid -->

                <nav class="pagination">
                    <span class="page-numbers current">1</span>
                    <a class="page-numbers" href="#">2</a>
                    <a class="next page-numbers" href="#">Next »</a>
                </nav>
                <br>


    <!-- .container -->
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="en">
<head>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>@yield('title-block')</title>
        <link rel="stylesheet" href="/css/woocommerce-layout.css" type="text/css" media="all">
        <link rel="stylesheet" href="/css/woocommerce-smallscreen.css" type="text/css" media="only screen and (max-width: 768px)">
        <link rel="stylesheet" href="/css/woocommerce.css" type="text/css" media="all">
        <link rel="stylesheet" href="/css/font-awesome.min.css" type="text/css" media="all">
        <link rel="stylesheet" href="/css/style.css" type="text/css" media="all">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald:400,500,700%7CRoboto:400,500,700%7CHerr+Von+Muellerhoff:400,500,700%7CQuattrocento+Sans:400,500,700" type="text/css" media="all">
        <link rel="stylesheet" href="/css/easy-responsive-shortcodes.css" type="text/css" media="all">

</head>
<body class="home page page-template page-template-template-portfolio page-template-template-portfolio-php">
<div id="page">
    <div class="container">
        <header id="masthead" class="site-header">
            <div class="site-branding">
                <h1 class="site-title"><a href="{{route('article.index')}}" rel="home">Moschino</a></h1>
                <h2 class="site-description">Minimalist Portfolio HTML Template</h2>
            </div>
            <nav id="site-navigation" class="main-navigation">
                <button class="menu-toggle">Menu</button>
                <a class="skip-link screen-reader-text" href="#">Skip to content</a>
                <div class="menu-menu-1-container">
                    <ul id="menu-menu-1" class="menu nav-menu">
                        <li><a href="{{route('article.index')}}">Home</a></li>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Shop</a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">Elements</a></li>
                        <li><a href="#">Contact</a></li>
                        <li><a href="#">Pages</a>
                            <ul class="sub-menu">
                                <li><a href="#">Portfolio Item</a></li>
                                <li><a href="#">Blog Article</a></li>
                                <li><a href="#">Shop Item</a></li>
                                <li><a href="#">Portfolio Category</a></li>
                            </ul>
                        </li>
                       @guest
                        <li><a href="{{route('login')}}">Login</a></li>
                        <li><a href="{{route('register')}}">Registry</a></li>
                        @endguest

                        @auth
                            <li><a href="{{route('article.create')}}">Create article</a></li>
                            <li>
                       <form method="post" action="{{route('logout')}}">
                           @csrf
                           <button type="submit">Logout</button>
                       </form>
                            </li>
                        @endauth
                    </ul>
                </div>
            </nav>
        </header>
        <!-- #masthead -->
        <div id="content" class="site-content">
            <div id="primary" class="content-area column full">
                <main id="main" class="site-main">
        @yield('content')
            </main>
            </div>
        </div>
        <!-- #content -->
    </div>
    <!-- .container -->
    <footer id="colophon" class="site-footer">
        <div class="container">
            <div class="site-info">
                <h1 style="font-family: 'Herr Von Muellerhoff';color: #ccc;font-weight:300;text-align: center;margin-bottom:0;margin-top:0;line-height:1.4;font-size: 46px;">Moschino</h1>
                <a target="blank" href="https://www.wowthemes.net/">© Moschino - Free HTML Template by WowThemes.net</a>
            </div>
        </div>
    </footer>
    <a href="#top" class="smoothup" title="Back to top"><span class="genericon genericon-collapse"></span></a>
</div>
<!-- #page -->
<script src="js/jquery.js"></script>
<script src="js/plugins.js"></script>
<script src="js/scripts.js"></script>
<script src="js/masonry.pkgd.min.js"></script>

</body>
</html>